include variable drag coefficient
linjonathan/tropical_cyclone_risk pull request #13
Opened 2024-12-10 19:10 UTC by linjonathan

Adds functionality for variable drag coefficient, which increases the decay rate over land. Fixes a previous issue where storms did not decay quickly enough over land, leading to positive biases in return period calculations for inland locations.

2025-02-03 10:34 UTC, NicolasColombi commented
@linjonathan Did you had a look at the Cd issue for the NI basin and NA ?

2025-02-03 17:28 UTC, linjonathan commented
I just added a fix [ae6b0b1](https://github.com/linjonathan/tropical_cyclone_risk/pull/13/commits/ae6b0b11d8c047a4ee32ea5eaa193fe741ee69c9) that might solve your issue. Let me know.

2025-02-04 13:53 UTC, NicolasColombi requested changes

2025-02-04 13:53 UTC, NicolasColombi commented on intensity/coupled_fast.py
> +        Cd = self._get_current_Cd(clon, clat)
Please add: `clon, clat = y[0],y[1]` before defining Cd

2025-02-04 13:54 UTC, NicolasColombi commented
> I just added a fix [ae6b0b1](https://github.com/linjonathan/tropical_cyclone_risk/pull/13/commits/ae6b0b11d8c047a4ee32ea5eaa193fe741ee69c9) that might solve your issue. Let me know.

It does indeed solve the issue, thanks.

2025-04-16 15:41 UTC, merged